### PR TITLE
Install: register with central and obtain token

### PR DESCRIPTION
**Pull request by kraman**
Connect to strongloop-internal/scrum-nodeops#806

### CODE REVIEW

**Comment by rmg** [comment]
+1 on adding ability to create an executor on install
-1 on removing the ability not to create an executor on install

Could it verify a token if one is given (and error if it is invalid) and only create a new executor if one isn't given?

Also, it seems I didn't do a very good job with the tests when I added them. There should be at least a test or two that provide a mock `slServiceInstall` that verifies that the command Array is correct.

**Comment by rmg** [comment]
The only thing I would change is so minor I won't even mention it, and the tests looks great.

LGTM once CI is green :-)

**Comment by rmg** [comment]
@slnode test please

**Comment by kraman** [comment]
@slnode test please

**Pull request merged**
